version: 0.2

phases:
  pre_build:
    commands:
      - echo PreBuild started on `date`
      - bash library_java/../gradlew clean install
      - bash ./gradlew lintDebug
      - echo PreBuild finished on `date`
  build:
    commands:
      - echo Build started on `date`
      - bash gradle assembleDebug
      - echo Build completed on `date`
  post_build:
    commands:
      - ls -ltr
      - find . -name *.apk
artifacts:
  files:
    - './app/build/outputs/apk/debug/app-debug.apk'
    - './app/build/reports/lint-results-debug.html'
    - './app/build/reports/lint-results-debug.xml'
    - './app/buildspec.yml'